{% set name = "aioconsole" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bac11286f1062613d2523ceee1ba81c676cd269812b865b66b907448a7b5f63e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - apython = aioconsole:run_apython

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - aioconsole

about:
  home: https://github.com/vxgmichel/aioconsole
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Asynchronous console and interfaces for asyncio
  description: |
    Asynchronous console and interfaces for asyncio
  doc_url: https://aioconsole.readthedocs.io/
  dev_url: https://github.com/vxgmichel/aioconsole

extra:
  recipe-maintainers:
    - vxgmichel
    - timkpaine
