{% set name = "aioconsole" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c0acb66b4e72d6606c9fa14ac9eb001a222c37c885b8fbdf65f41824cfa855f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - apython = aioconsole:run_apython

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - aioconsole

about:
  home: https://github.com/vxgmichel/aioconsole
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Asynchronous console and interfaces for asyncio
  description: |
    Asynchronous console and interfaces for asyncio
  doc_url: https://aioconsole.readthedocs.io/
  dev_url: https://github.com/vxgmichel/aioconsole

extra:
  recipe-maintainers:
    - vxgmichel
    - timkpaine
